### ISSUE TITLE
Add border to context menu

### ISSUE THREAD

**Issue by GaryHilares** [GaryNLOL/Supple-Crystal#1]
**Is your feature request related to a problem? Please describe.**
It is hard to see the context menu when it is in a white background.

**Describe the solution you'd like**
I would like the context menu to have a border.

**Describe alternatives you've considered**
Personally, I think that the best option would be a thin black border. However, I'm open to suggestions.

**Comment by oneamanish** [comment]
see my pull req.

**Comment by GaryHilares** [comment]
I've looked at it, but I didn't understand how it solves this issue.
